openapi: 3.0.0
info:
  version: 0.0.0
  title: Shipping Label API
  description: 送り状発行API
paths:
  /issue:
    post:
      tags:
        - shippingLabels
      summary: 送り状登録
      description: クライアントが入力する情報をもとにユーザ情報を登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - deliveryCode
                properties:
                  deliveryCode:
                    description: 配送先の店舗コード
                    type: string
                    example: '1234567890'
                  deliveryDate:
                    description: 配送希望日
                    type: string
                    format: date
                    example: '2025-01-01'
                  shippingDate:
                    description: 配送日
                    type: string
                    format: date
                    example: '2025-01-05'
                  note:
                    description: 送り状に記載するメモ
                    type: string
                    example: 客注での配送です
      responses:
        '200':
          description: ユーザ情報登録成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - shippingLabelId
                  - trackingNumber
                properties:
                  shippingLabelId:
                    type: string
                    example: '1234567890'
                  trackingNumber:
                    type: string
                    example: '1234567890'
        '400':
          description: 入力エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  errCode:
                    type: integer
                    format: number
                    example: 100
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  errCode:
                    type: integer
                    format: number
                    example: 100
  /download:
    get:
      tags:
        - shippingLabels
      summary: 送り状取得
      description: shippingLabelIdをもとに送り状をダウンロードする
      parameters:
        - in: query
          name: shippingLabelId
          description: 送り状ID
          required: true
          schema:
            type: string
            example: '1234567890'
      responses:
        '200':
          description: 取得成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - download_url
                properties:
                  download_url:
                    type: string
                    format: uri
                    example: 'http://aaaaaa.com'
        '204':
          description: 送り状が存在しない
        '404':
          description: 存在しない
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  errCode:
                    type: integer
                    format: number
                    example: 100
